apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  annotations:
    "helm.sh/hook-weight": "-100"
 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: nginx:1.210.1
        ports:
        - containerPort: 80
        env:
        - name: MESSAGE
          value: "{{ .Values.message }}"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: test-post-sync-check
  annotations:
    "helm.sh/hook-weight": "200"
    "argocd.argoproj.io/hook": "PostSync"
spec:
  template:
    spec:
      containers:
      - name: post-sync-check
        image: busybox:latest # Replace with the image you want to use for your post-sync check
        command: ['sh', '-c', 'echo "Deployment is fine!"'] # Replace with your actual post-sync check command(s)
      restartPolicy: Never
  backoffLimit: 0
